### ISSUE TITLE
Save finger travel time. 

### ISSUE THREAD

**Issue by sarojkh** [nrayamajhee/dotfiles#1]
In `.vimrc`, add the following!
```
inoremap jj <ESC>
```

Apparently, `jj` doesn't require moving away from where your right-index finger would normally rest in the keyboard. Also, its highly unlikely you would ever need to type `jj` in insert mode.

**Comment by sarojkh** [comment]
Also, my another favorite and something that helps me every hour is the following.
```
set relativenumber       
```

**Comment by nrayamajhee** [comment]
Awesome! Didn't know about relativenumber. I actually went with https://jeffkreeftmeijer.com/vim-number/#automatic-toggling-between-line-number-modes.
Adopted your recommenedations: 1bb283f586d858e8fbdaa51e0d43727b2e0fc900
